apiVersion: v2
description: Landing page for Farming Front Door
name: ffc-ffd-landing-page
# this version is automatically updated in the build pipeline
version: 1.0.0
dependencies:
- name: ffc-helm-library
  version: 4.0.0
  repository: https://raw.githubusercontent.com/defra/ffc-helm-repository/master/
