services:
  ffc-ffd-landing-page:
    build:
      context: .
      target: production
    image: ffc-ffd-landing-page
    container_name: ffc-ffd-landing-page
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-ffd-landing-page-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      PRIVATE_GATEWAY_HOST: ${PRIVATE_GATEWAY_HOST:-http://ffc-ffd-proxy:3000}
      PUBLIC_GATEWAY_HOST: ${PUBLIC_GATEWAY_HOST:-http://localhost:3000}
