services:
  ffc-ffd-landing-page:
    build:
      context: .
      target: production
    image: ffc-ffd-landing-page
    container_name: ffc-ffd-landing-page
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-ffd-landing-page-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      GATEWAY_URL: ${GATEWAY_URL:-http://localhost:3000}
