{{- include "ffc-helm-library.container-secret" (list . "ffc-ffd-landing-page.container-secret") -}}
{{- define "ffc-ffd-landing-page.container-secret" -}}
stringData:
  {{- if .Values.appInsights.connectionString }}
  APPINSIGHTS_CONNECTIONSTRING: {{ quote .Values.appInsights.connectionString }}
  {{- end }}
{{- end -}}
