{{- include "ffc-helm-library.azure-ingress" (list . "ffc-ffd-landing-page.ingress") -}}
{{- define "ffc-ffd-landing-page.ingress" -}}
{{- if not .Values.pr -}}
metadata:
  annotations:
    nginx.org/mergeable-ingress-type: minion
    nginx.ingress.kubernetes.io/server-snippet: |
      location / {
        return 301 https://{{ .Values.workstream }}.{{ .Values.ingress.server }}{{ .Values.ingress.path }}$request_uri;
      }
spec:
  rules:
  - host: {{ .Values.workstream }}.{{ .Values.ingress.server }}
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.name }}
            port:
              number: 80
{{- else -}}
metadata:
  annotations:
    nginx.ingress.kubernetes.io/server-snippet: |
      location / {
        return 301 https://{{ .Values.name }}-{{ .Values.pr }}.{{ .Values.ingress.server }}{{ .Values.ingress.path }}$request_uri;
      }
spec:
  rules:
  - host: {{ .Values.name }}-{{ .Values.pr }}.{{ .Values.ingress.server }}
    http:
      paths:
      - path: {{ .Values.ingress.path }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.name }}
            port:
              number: {{ .Values.container.port }}
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.name }}
            port:
              number: {{ .Values.container.port }}
{{- end -}}
{{- end -}}
